### ISSUE TITLE
Make the Streamlit demo to work in testing environment

### ISSUE THREAD

**Issue by aaitor** [nevermined-io/streamlit#2]
Currently is working connected to staging. Make it work with this asset existing on testing:
https://testing.nevermined.app/en/webservice/did%3Anv%3A5a06236a0bb1620c171a17a2e4d82935b1b63274011aeb1d9efcce87e83f0fee

Document as a tutorial using this: https://discuss.streamlit.io/t/get-paid-for-your-streamlit-generative-ai-app/59195

Ask @aaitor about the Elvis copilot endpoints.

```[tasklist]
### Tasks
- [x] Change demo to testing asset
- [x] Update streamlit post to use testing environment
- [x] Document Streamlit as a tutorial (divide in a few tutorials)
```

**Comment by r-marques** [comment]
namespace one-testing
